### PR TITLE
Case insensitive user email query

### PR DESCRIPTION
**Pull request by sethkrasnianski**
Closes https://github.com/mojotech/standup-api/issues/31

### CODE REVIEW

**Comment by sethkrasnianski** [comment]
:+1:

**Comment by begizi** [comment]
:+1:

**Comment by begizi** [comment]
Fails to compile `./user.go:54: type unicode.SpecialCase is not an expression`

**Comment by begizi** [comment]
`SpecialCase` is a type, and the only constants set with that type are TurkishCase and AzeriCase. By default, `ToLower` will handle special characters (https://play.golang.org/p/y80w56UqSd) with the exception of some Turkish and Azeri characters (which I don't think we'll have to deal with).

Let's just use `strings.ToLower()` for all lower case conversions.

**Pull request merged**
